n: update node version manager 'n' to 2.1.3

diff --git a/home/nodejs/.bin/n b/home/nodejs/.bin/n
--- a/home/nodejs/.bin/n
+++ b/home/nodejs/.bin/n
@@ -4,7 +4,7 @@
 # Setup.
 #
 
-VERSION="2.1.0"
+VERSION="2.1.3"
 UP=$'\033[A'
 DOWN=$'\033[B'
 N_PREFIX=${N_PREFIX-/usr/local}
@@ -284,7 +284,7 @@ versions_paths() {
   find $BASE_VERSIONS_DIR -maxdepth 2 -type d \
     | sed 's|'$BASE_VERSIONS_DIR'/||g' \
     | egrep "/[0-9]+\.[0-9]+\.[0-9]+$" \
-    | sort -k 1 -k 2,2n -k 3,3n -t .
+    | sort -k 1,1 -k 2,2n -k 3,3n -t .
 }
 
 #
@@ -358,12 +358,30 @@ erase_line() {
 #
 # Check if the HEAD response of <url> is 200.
 #
-
 is_ok() {
   if command -v curl > /dev/null; then
     $GET -Is $1 | head -n 1 | grep 200 > /dev/null
   else
     $GET -S --spider 2>&1 $1 | head -n 1 | grep 200 > /dev/null
+  fi
+}
+
+#
+# Check if the OSS(Object Storage Service) mirror is ok.
+#
+is_oss_ok() {
+  if command -v curl > /dev/null; then
+    if $GET -Is $1 | head -n 1 | grep 302 > /dev/null; then
+      is_oss_ok $GET -Is $1 | grep Location | awk -F ': ' '{print $2}'
+    else
+      $GET -Is $1 | head -n 1 | grep 200 > /dev/null
+    fi
+  else
+    if $GET -S --spider 2>&1 $1 | head -n 1 | grep 302 > /dev/null; then
+      is_oss_ok $GET -S --spider 2>&1 $1 | grep Location | awk -F ': ' '{print $2}'
+    else
+      $GET -S --spider 2>&1 $1 | head -n 1 | grep 200 > /dev/null
+    fi
   fi
 }
 
@@ -438,8 +456,6 @@ activate() {
   if test "$version" != "$active"; then
     local dir=$BASE_VERSIONS_DIR/$version
     for subdir in bin lib include share; do
-      echo $N_PREFIX/$subdir
-      echo $dir/$subdir
       if test -L "$N_PREFIX/$subdir"; then
         find "$dir/$subdir" -mindepth 1 -maxdepth 1 -exec cp -fR "{}" "$N_PREFIX/$subdir" \;
       else
@@ -484,7 +500,7 @@ install() {
   local version=${1#v}
 
   local dots=$(echo $version | sed 's/[^.]*//g')
-  if test ${#dots} -eq 1; then
+  if test ${#dots} -lt 2; then
     version=$($GET 2> /dev/null ${MIRROR[DEFAULT]} \
       | egrep "</a>" \
       | egrep -o '[0-9]+\.[0-9]+\.[0-9]+' \
@@ -512,7 +528,7 @@ install() {
   log install ${BINS[$DEFAULT]}-v$version
 
   local url=$(tarball_url $version)
-  is_ok $url || abort "invalid version $version"
+  is_ok $url || is_oss_ok $url || abort "invalid version $version"
 
   log mkdir $dir
   mkdir -p $dir
